spring.application.name=CampusLeague
server.port=${PORT}
spring.web.resources.locations=http://localhost:4200

# base de datos
spring.datasource.url=${DB_URL}?createDatabaseIfNotExist=true
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# security
spring.jwt.secret=${KEY}
spring.jwt.expiration=3600000

spring.jpa.open-in-view=false
